### ISSUE TITLE
Making structures optional.

### ISSUE THREAD

**Issue by fubin1999** [fubin1999/glytrait#7]
# Optional structures

Some users may not have glycan structure information. To make GlyTrait more flexible, two solutions will be provided:

1. If the samples are human serum or serum IgG N-glycans, a built-in structure database will be used. N-glycan structures in human serum and serum IgG have been thoroughly determined.
2. Otherwise, a derived trait set designed for composition will be used.

# New design

1. The basic usage remains unchanged, i.e., the user provided an input file with a "Structure" column using this command:
```
glytrait data.csv
```

2. The "Glycan ID" column is renamed into "Composition". If a "Structure" column is provided, the values in the "Composition" column will act as IDs. However, when the structure is not provided and the user uses the "-c" option (see below), the "Composition" column will be used to generate composition-based derived traits.
The new input file format would be:

| Composition | Structure | Sample 1 | Sample 2 | Sample 3 |
| ------------- | --------- | --------- | --------- | ---------- |
| H4N2 | RES... | 0.23 | 0.12 | 0.22 |
| ... | ... | ... | ... | ... |

3. The user could also provide a separate structure file, with the first column as "Composition" and second column as "Structure", using the "-s" or "--structure" option:
```
glytrait data.csv -s structure.csv
```
The format of structure.csv is:

| Composition | Structure |
| ------------- | --------- |
| H4N2 | RES... |
| ... | ... |

In this case, the input file should not have the "Structure" column:

| Composition | Sample 1 | Sample 2 | Sample 3 |
| ------------- | --------- | --------- | --------- |
| H4N2 | 0.23 | 0.12 | 0.22 |
| ... | ... | ... | ... |

If the abundance file has compositions without corresponding structure in the structure file, an error will be raised. However, the structure file could contain glycans not in the abundance file, and GlyTrait will just ignore these glycans. This feature is especially useful when the user has a pre-defined glycan structure database with all possible glycans.

4. Remove the short option name for "--sia_linkage" as it conflicts with the new "structure" option.

5. Apart from providing a structure file or a "Structure" column in the input file, the user can also use the built-in structure database with "-d" or "--database" option:
```
glytrait data.csv -d serum
```
We only support "serum" and "IgG" for these samples have been thoroughly studied.

6. If the user doesn't have structure information, and the samples are not serum or serum IgG, composition-based derived traits could be calculated using the "-c" or "--composition" option:
```
glytrait data.csv -c
```
In this case, GlyTrait will leverage the "Composition" column in the input file. Sialic-acid-linkage-specific condensed composition format (e.g. H5N4E1L1) is supported. Note that in the "structure" mode the sanity of the "Composition" column is not checked, but in the "composition" mode the values should be valid glycan condensed composition.

7. An error will be raised if no "Structure" column is found and neither "-d" or "-c" option is used.

# TODOs

- [x] Add the "-s" option.
- [x] Add built-in database (the "-d" option).
- [x] Add composition-based derived traits (the "-c" option).
